# Generated by Django 5.2.7 on 2025-11-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='url_source',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
    ]
