# Generated by Django 5.2.7 on 2025-11-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='average_rating',
            new_name='ratings_sum',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='times_cooked',
        ),
    ]
