# Generated by Django 5.2.7 on 2025-11-05 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_comment_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='api.recipe'),
        ),
    ]
