# Generated by Django 5.2.7 on 2025-11-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_meal_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='times_cooked',
        ),
    ]
