# Generated by Django 5.2.7 on 2025-11-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_recipe_times_cooked'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='times_cooked',
            field=models.PositiveIntegerField(default=0, verbose_name='number of times cooked'),
        ),
    ]
