# Generated by Django 5.2.7 on 2025-11-05 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_recipe_times_cooked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='meal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='comment', serialize=False, to='api.meal'),
        ),
    ]
